version: "3"

services:
  whoami:
    container_name: whoami
    labels:
      traefik.docker.network: "traefik-net"
      traefik.enable: "true"
      traefik.http.routers.whoami.entrypoints: "https"
      traefik.http.routers.whoami.middlewares: "default@file"
      traefik.http.routers.whoami.rule: "Host(`whoami.t99ltd.info`)"
      traefik.http.routers.whoami.tls.certresolver: "letsEncrypt@file"
      traefik.http.routers.whoami.tls.options: "modern@file"
      traefik.http.routers.whoami.tls: "true"
      traefik.http.services.whoami.loadbalancer.server.port: 80
      traefik.http.services.whoami.loadbalancer.sticky.cookie.httpOnly: "true"
      traefik.http.services.whoami.loadbalancer.sticky.cookie.secure: "true"
    image: "traefik/whoami"
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: overlay
    external: true
