version: '3'
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    labels:
      # - traefik.enable=true
      # - traefik.http.routers.portainer.rule=Host(`portainer.t99ltd.foundation`)
      # - traefik.http.routers.portainer.entrypoints=http,https
      # - traefik.http.routers.portainer.tls=true
      # - traefik.http.routers.portainer.tls.certresolver=default
      # - traefik.http.services.portainer.loadbalancer.server.port=9000
      traefik.docker.network: "traefik-net"
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: "https"
      traefik.http.routers.portainer.middlewares: "default@file"
      traefik.http.routers.portainer.rule: "Host(`portainer.t99ltd.info`)"
      traefik.http.routers.portainer.tls.certresolver: "letsEncrypt"
      traefik.http.routers.portainer.tls.options: "modern@file"
      traefik.http.routers.portainer.tls: "true"
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      traefik.http.services.portainer.loadbalancer.sticky.cookie.httpOnly: "true"
      traefik.http.services.portainer.loadbalancer.sticky.cookie.secure: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    networks:
      - traefik-net
networks:
  traefik-net:
    driver: overlay
    external: true 
